	</div>
</div>

<div class="col col-12">
	<div class="exploratory-map-block row <?= $mapType ?>" data-markers="<?= $this->escapeHtml( json_encode( $markers ) ) ?>" data-basemap="<?= $this->escapeHtml( $basemaps[0]['url'] ) ?>" data-access-token="<?= $this->escapeHtml( $accessToken ) ?>">
	
		<div class="map-container">

			<?php if( $mapType == 'story' ) { ?>
				<div class="map-arrow" data-direction="prev"></div>
				<div class="map-arrow" data-direction="next"></div>
			<?php } ?>

			<?php if( $mapType == 'layered' ) { ?>

				<div class="layer-forms">

					<form class="layer-form layer-selector" data-layer-type="overlay">
						<h3>Historicals maps</h3>
						<!-- <input type="checkbox" name="overlay" value="" id="overlay-null"/> -->
						<?php foreach ( $overlays as $index => $value) { ?>
							<input class="pseudo-radio" type="checkbox" name="overlay" value="<?= $value['url'] ?>" id="overlay-<?= $index ?>"/>
							<label for="overlay-<?= $index ?>"><?= $value['name'] ?></label>
						<?php } ?>
					</form>

					<form class="layer-form layer-filter" data-layer-type="markers">
						<h3>Incident type</h3>
						<input type="checkbox" name="markers" value="Type 1" id="type-1"/>
						<label for="type-1">Type 1</label>

						<input type="checkbox" name="markers" value="Type 2" id="type-2"/>
						<label for="type-2">Type 2</label>
					</form>

					<form class="layer-form layer-selector" data-layer-type="basemap">
						<h3>Basemaps</h3>
						<?php foreach ( $basemaps as $index => $value) { ?>
							<input type="radio" name="basemap" value="<?= $value['url'] ?>" id="basemap-<?= $index ?>" <?= $index === 0 ? "checked" : null ?>/>
							<label for="basemap-<?= $index ?>"><?= $value['name'] ?></label>
						<?php } ?>
					</form>
					
				</div>
			<?php } ?>

		</div>
		<div class="item-showcase">
		  <?php foreach ( $markers as $markerIndex => $marker ) {
		  	$item = $marker['item'];
		  	if( isset( $marker['coords'] ) ) {
		  		$coords = $marker['coords'];
		  		$markerCoords = '[' . $coords . ']'; ?>
			    <div class="item col-6 col-md-4 col-lg-3" data-item-api="<?= $api ?>" data-index="<?= ( $markerIndex + 1 ) ?>"  data-marker-coords="<?= $this->escapeHtml( $markerCoords ) ?>">
			      <span class="title"><?= $marker['title'] ?></span>
			    </div>
		  <?php }
			} ?>
		</div>
	</div>
</div>
<div class="col col-4"></div>
<div class="col col-8">
	<div class="column">
