	</div>
</div>

<div class="col col-12">

	<?php $map_id = uniqid(); ?>

	<div class="exploratory-map-block row <?= $mapType ?>" data-markers="<?= $this->escapeHtml( json_encode( $markers ) ) ?>" data-basemap="<?= $this->escapeHtml( $basemaps[0]['url'] ) ?>" data-access-token="<?= $this->escapeHtml( $accessToken ) ?>" data-map-type="<?= $mapType ?>" id="<?= $map_id ?>">
	
		<div class="map-container">

			<?php if( $mapType == 'story' ) { ?>
				<div class="map-arrow" data-direction="prev"></div>
				<div class="map-arrow" data-direction="next"></div>
			<?php } ?>

			<?php if( $mapType == 'layered' ) { ?>

				<div class="layer-forms">

					<form class="layer-form layer-filter" data-layer-type="markers">
						<h3>Filters</h3>
						<input type="checkbox" name="markers" value="" id="type-landmarks" checked />
						<label for="type-landmarks">Landmarks</label>
						<?php foreach ( $types as $index => $value ) { ?>
							<input type="checkbox" name="markers" value="<?= $value ?>" id="type-<?= $index; ?>" checked />
							<label for="type-<?= $index; ?>"><?= $value; ?></label>
						<?php } ?>
					</form>

					<form class="layer-form layer-selector" data-layer-type="overlay">
						<h3>Historicals maps</h3>
						<!-- <input type="checkbox" name="overlay" value="" id="overlay-null"/> -->
						<?php foreach ( $overlays as $index => $value) { ?>
							<input class="pseudo-radio" type="checkbox" name="overlay" value="<?= $value['url'] ?>" id="overlay-<?= $index ?>"/>
							<label for="overlay-<?= $index ?>"><?= $value['name'] ?></label>
						<?php } ?>
					</form>

					<form class="layer-form layer-selector" data-layer-type="basemap">
						<h3>Basemaps</h3>
						<?php foreach ( $basemaps as $index => $value) { ?>
							<input type="radio" name="basemap" value="<?= $value['url'] ?>" id="basemap-<?= $index ?>" <?= $index === 0 ? "checked" : null ?>/>
							<label for="basemap-<?= $index ?>"><?= $value['name'] ?></label>
						<?php } ?>
					</form>
					
				</div>
			<?php } ?>

		</div>
		<div class="item-showcase">
		  <?php foreach ( $markers as $markerIndex => $marker ) {
		  	$item = $marker['item'];
		  	if( isset( $marker['coords'] ) ) {
		  		$coords = $marker['coords'];
		  		$markerCoords = '[' . $coords . ']'; ?>
			    <div class="item col-6 col-md-4 col-lg-3" data-item-api="<?= $item ?>" data-index="<?= ( $markerIndex + 1 ) ?>"  data-marker-coords="<?= $this->escapeHtml( $markerCoords ) ?>">
			      <span class="title"><?= $marker['title'] ?></span>
			    </div>
		  <?php }
			} ?>
		</div>
	</div>
</div>
<div class="col col-4"></div>
<div class="col col-8">
	<div class="column">
